# Generated by Django 4.2.20 on 2025-06-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="decimal",
            field=models.CharField(
                default=None, max_length=100, verbose_name="Децимальный номер"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["decimal"], name="parts_decimal_f4f956_idx"),
        ),
    ]
