# Generated by Django 4.2.20 on 2025-06-30 13:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinemodule",
            name="link",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machinemodule_link",
                to="core.machinemodule",
                verbose_name="Связь",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the machine in the association.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="module_machines",
                to="core.machine",
                verbose_name="Машина",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machine_modules",
                to="core.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent_module",
                to="core.module",
                verbose_name="Родительский модуль",
            ),
        ),
    ]
