# Generated by Django 4.2.20 on 2025-06-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinemodule",
            name="parent_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent_modules",
                to="core.module",
                verbose_name="Родительский модуль",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the machine in the association.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machine_modules",
                to="core.machine",
                verbose_name="Машина",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="module",
            field=models.ForeignKey(
                help_text="Reference to the module in the association.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="module_machines",
                to="core.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="machinemodule",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AddConstraint(
            model_name="machinemodule",
            constraint=models.UniqueConstraint(
                fields=("module", "parent_module"), name="unique_parent_module_module"
            ),
        ),
    ]
