# Generated by Django 4.2.20 on 2025-07-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_machinemodule_link_alter_machinemodule_machine_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machinemodule",
            options={
                "ordering": ["id"],
                "verbose_name": "Связь Модуль-Машина",
                "verbose_name_plural": "Связи Модуль-Машина",
            },
        ),
        migrations.RemoveField(
            model_name="machinemodule",
            name="level",
        ),
        migrations.RemoveField(
            model_name="machinemodule",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="machinemodule",
            name="link",
        ),
        migrations.RemoveField(
            model_name="machinemodule",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="machinemodule",
            name="tree_id",
        ),
    ]
