# Generated by Django 4.2.20 on 2025-06-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_machinemodule_parent_module_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="parent",
        ),
    ]
