# Generated by Django 4.2.20 on 2025-06-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_part_decimal_part_parts_decimal_f4f956_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the association was created.",
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment about the module-machine association.",
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь Модуль-Машина",
                "verbose_name_plural": "Связи Модуль-Машина",
                "db_table": "module_machines",
            },
        ),
        migrations.AlterModelOptions(
            name="modulepart",
            options={
                "ordering": ["id"],
                "verbose_name": "Связь Изделие-Модуль",
                "verbose_name_plural": "Связи Изделие-Модуль",
            },
        ),
        migrations.AlterModelOptions(
            name="part",
            options={
                "ordering": ["name"],
                "verbose_name": "Изделие",
                "verbose_name_plural": "Изделия",
            },
        ),
        migrations.RemoveIndex(
            model_name="module",
            name="modules_machine_68534f_idx",
        ),
        migrations.RemoveField(
            model_name="module",
            name="machine",
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название модуля"),
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="part_modules",
                to="core.part",
                verbose_name="Изделие",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание изделия"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="modulemachine",
            name="machine",
            field=models.ForeignKey(
                help_text="Reference to the machine in the association.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.machine",
                verbose_name="Машина",
            ),
        ),
        migrations.AddField(
            model_name="modulemachine",
            name="module",
            field=models.ForeignKey(
                help_text="Reference to the module in the association.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="machines",
            field=models.ManyToManyField(
                related_name="modules",
                through="core.ModuleMachine",
                to="core.machine",
                verbose_name="Машина",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modulemachine",
            unique_together={("module", "machine")},
        ),
    ]
