# Generated by Django 4.2.20 on 2025-05-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_part_description_part_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blueprint",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="module",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.manufacturer",
                verbose_name="Производитель",
            ),
        ),
    ]
