# Generated by Django 4.2.20 on 2025-05-16 06:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0003_remove_blueprint_manufacturer_module_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "Пользователь-роль ссылка",
                "verbose_name_plural": "Пользователь-роль ссылки",
            },
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, утвердивший чертёж",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_blueprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Утвердивший",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="chief_designer",
            field=models.ForeignKey(
                blank=True,
                help_text="Главный конструктор проекта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chief_designed_blueprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Главный конструктор",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, разработавший чертёж",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developed_blueprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Разработчик",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="lead_designer",
            field=models.ForeignKey(
                blank=True,
                help_text="Ответственный ведущий конструктор проекта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_designed_blueprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ведущий конструктор",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="naming_scheme",
            field=models.CharField(
                help_text="Схема наименования для идентификации чертежа",
                max_length=100,
                verbose_name="Схема наименования",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="scale",
            field=models.CharField(
                blank=True,
                help_text="Масштаб чертежа, например '1:10'",
                max_length=50,
                verbose_name="Масштаб",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="scheme_file",
            field=models.FileField(
                help_text="Загруженный файл чертежа в формате PDF",
                upload_to="blueprints/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Файл чертежа (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="step_file",
            field=models.FileField(
                help_text="3D-модель в формате STEP для CAD-систем",
                upload_to="steps/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["step"]
                    )
                ],
                verbose_name="Файл чертежа (STEP)",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, проверивший чертёж",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_blueprints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверяющий",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Версия чертежа, например 'v1.0'",
                max_length=50,
                verbose_name="Версия",
            ),
        ),
        migrations.AlterField(
            model_name="blueprint",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вес изделия в килограммах (может быть пустым)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Вес (кг)",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, выполнивший изменение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь, который изменил",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="changed_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Время, когда было произведено изменение",
                verbose_name="Дата изменения",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="column_name",
            field=models.CharField(
                help_text="Название поля, которое было изменено",
                max_length=100,
                verbose_name="Имя столбца",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="log_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Идентификатор лога"
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="new_value",
            field=models.TextField(
                blank=True,
                help_text="Значение после изменения",
                null=True,
                verbose_name="Новое значение",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="old_value",
            field=models.TextField(
                blank=True,
                help_text="Значение до изменения",
                null=True,
                verbose_name="Старое значение",
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="record_id",
            field=models.BigIntegerField(
                help_text="Идентификатор измененной записи", verbose_name="ID записи"
            ),
        ),
        migrations.AlterField(
            model_name="changeslog",
            name="table_name",
            field=models.CharField(
                help_text="Название таблицы, в которой произошло изменение",
                max_length=100,
                verbose_name="Имя таблицы",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(
                help_text="Страна клиента", max_length=100, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="Название клиента (уникальное значение)",
                max_length=150,
                unique=True,
                verbose_name="Имя клиента",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон клиента (необязательное поле)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+99999999999'. От 9 до 15 цифр.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.CharField(
                help_text="Страна, в которой расположен производитель",
                max_length=100,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Язык общения с производителем (необязательно)",
                max_length=50,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                help_text="Название производителя (уникальное значение)",
                max_length=150,
                unique=True,
                verbose_name="Название производителя",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон производителя (необязательное поле)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+99999999999'. От 9 до 15 цифр.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновлено пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи.",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_parts",
                to="core.module",
                verbose_name="Module",
            ),
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="part_modules",
                to="core.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of parts in the module",
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи.",
                verbose_name="Создано",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts_manufactured",
                to="core.manufacturer",
                verbose_name="Производители",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновлено пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи.",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date joined"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups the user belongs to.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+99999999999'. От 9 до 15 цифр.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
    ]
