# Generated by Django 4.2.20 on 2025-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_modulemachine_alter_modulepart_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе"),
                    ("completed", "Завершена"),
                    ("abandoned", "Брошена"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
    ]
