# Generated by Django 4.2.20 on 2025-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_part_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="decimal",
            field=models.CharField(
                blank=True,
                help_text="Decimal number of the part, used for identification",
                max_length=100,
                null=True,
                verbose_name="Децимальный номер",
            ),
        ),
    ]
