# Generated by Django 4.2.20 on 2025-05-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_userrole_options_alter_blueprint_approver_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "Связь Пользователь-Роль",
                "verbose_name_plural": "Связи Пользователь-Роль",
            },
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_parts",
                to="core.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="modulepart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="part_modules",
                to="core.part",
                verbose_name="Деталь",
            ),
        ),
    ]
