# Generated by Django 4.2.20 on 2025-05-29 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_task_alter_modulepart_options_tasklink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=None, verbose_name="Создано"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе"),
                    ("completed", "Завершена"),
                    ("abandoned", "Брошена"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, получающий задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, отправивший задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
    ]
