# Generated by Django 5.2.4 on 2025-07-30 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kalmar32'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='video_url',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='photo_video_url',
            field=models.URLField(blank=True, help_text='URL фотографии. видео преобразователей', validators=[django.core.validators.URLValidator()], verbose_name='Фото, видео'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL фото оборудования', validators=[django.core.validators.URLValidator()], verbose_name='Фото'),
        ),
    ]
