# Generated by Django 5.2.4 on 2025-08-06 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_kalmar32_flash_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalmar32',
            name='flash_drive',
            field=models.CharField(blank=True, help_text="Наличие флеш-накопителя с ПО 'Кальмар 32+'", max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Флеш-накопитель с ПО'),
        ),
    ]
