# Generated by Django 5.2.4 on 2025-08-06 09:41

import core.models.report
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_kalmar32_flash_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.datetime.now, help_text='Дата создания отчета', verbose_name='Дата отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Точная дата и время создания отчета', verbose_name='Дата и время создания')),
                ('json_report', models.FileField(help_text='Файл отчета в формате JSON (report.json)', upload_to=core.models.report.report_json_upload_to, verbose_name='JSON отчет')),
                ('pdf_report', models.FileField(help_text='Файл отчета в формате PDF (report.pdf)', upload_to=core.models.report.report_pdf_upload_to, verbose_name='PDF отчет')),
                ('rail_record_before', models.FileField(help_text='Архив с записями рельсов до обслуживания (before_to/rail_record.zip)', upload_to=core.models.report.rail_record_before_upload_to, verbose_name='Запись рельсов (до)')),
                ('rail_record_after', models.FileField(help_text='Архив с записями рельсов после обслуживания (after_to/rail_record.zip)', upload_to=core.models.report.rail_record_after_upload_to, verbose_name='Запись рельсов (после)')),
                ('kalmar', models.ForeignKey(help_text='Связанное оборудование Kalmar32', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.kalmar32', verbose_name='Оборудование Кальмар32')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_report_created_a1bef3_idx'), models.Index(fields=['report_date'], name='core_report_report__60e3df_idx')],
            },
        ),
    ]
