# Generated by Django 5.2.4 on 2025-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='core_report_created_a1bef3_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AddField(
            model_name='report',
            name='number_to',
            field=models.CharField(choices=[('TO-1', 'TO-1'), ('TO-2', 'TO-2'), ('TO-3', 'TO-3')], default=None, max_length=10, verbose_name='Номер проведенного ТО'),
            preserve_default=False,
        ),
    ]
