# Generated by Django 5.2.4 on 2025-08-20 06:14

import core.models.report
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='json_report',
            field=models.FileField(blank=True, help_text='Файл отчета в формате JSON (report.json)', upload_to=core.models.report.report_json_upload_to, verbose_name='JSON отчет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='Файл отчета в формате PDF (report.pdf)', upload_to=core.models.report.report_pdf_upload_to, verbose_name='PDF отчет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rail_record_after',
            field=models.FileField(blank=True, help_text='Архив с записями рельсов после обслуживания (after_to/rail_record.zip)', upload_to=core.models.report.rail_record_after_upload_to, verbose_name='Запись рельсов (после)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rail_record_before',
            field=models.FileField(blank=True, help_text='Архив с записями рельсов до обслуживания (before_to/rail_record.zip)', upload_to=core.models.report.rail_record_before_upload_to, verbose_name='Запись рельсов (до)'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('kalmar', 'report_date', 'number_to'), name='unique_report_per_kalmar_by_date'),
        ),
    ]
