# Generated by Django 5.2.4 on 2025-08-20 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_report_json_report_alter_report_pdf_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalmar32',
            name='case_number',
            field=models.CharField(blank=True, help_text='Номер кейса для хранения оборудования', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Номер кейса'),
        ),
    ]
