# Generated by Django 5.2.4 on 2025-10-13 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_kalmar32_case_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='aos_block',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='battery_case',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='battery_charger',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='calibration_certificate',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='calibration_date',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='co3r_measure',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='first_phased_array_converters',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='flash_drive',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='has_ethernet_cable',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='has_tablet_screws',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='has_tool_kit',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='manual_inclined',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='photo_video_url',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='second_phased_array_converters',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='software_check',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='straight',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='tablet_charger',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='weight',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='ac_dc_charger_adapter_battery',
            field=models.CharField(blank=True, help_text='AC/DC Charger adapter for battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC адаптер зарядки для батареи'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='ac_dc_power_adapter_dell',
            field=models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC адаптер питания для Dell 7230'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='calibration_block_so_3r',
            field=models.CharField(blank=True, help_text='Calibration bloc SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Калибровочный блок SO-3R'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='dc_battery_box',
            field=models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Батарейный блок DC'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='dc_charger_adapter_battery',
            field=models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC адаптер зарядки от батареи для Dell 7230'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='has_dc_cable_battery',
            field=models.BooleanField(default=False, help_text='DC Cable from battery box', verbose_name='DC кабель от батарейного блока'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='has_ethernet_cables',
            field=models.BooleanField(default=False, help_text='Ethernet cables', verbose_name='Ethernet кабель'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='has_installed_nameplate',
            field=models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Установленная табличка с серийным номером'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='has_repair_tool_bag',
            field=models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Ремонтный инструмент с сумкой'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='manual_probs_36',
            field=models.CharField(blank=True, help_text='Manual probs 36° RA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной преобразователь 36°'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='pc_tablet_dell_7230',
            field=models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Планшет Dell 7230'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='personalised_name_tag',
            field=models.CharField(blank=True, help_text='Personalised name tag', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Персонализированная бирка'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='software_installer',
            field=models.FileField(blank=True, help_text='Файл инсталлятора для программного обеспечения', null=True, upload_to='kalmar32_installers/', verbose_name='Инсталлятор ПО'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='straight_probs_0',
            field=models.CharField(blank=True, help_text='Straight probs 0° RA5.0L16 0.6x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Прямой преобразователь 0°'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='ultrasonic_phased_array_pulsar',
            field=models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/64 established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ультразвуковая фазированная решетка PULSAR OEM 16/64'),
        ),
        migrations.DeleteModel(
            name='Converter',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
