# Generated by Django 5.2.4 on 2025-10-16 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_kalmar32_aos_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='personalised_name_tag',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='case_number',
            field=models.CharField(blank=True, help_text='Номер кейса для хранения оборудования', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Номер кейса'),
        ),
    ]
