# Generated by Django 5.2.4 on 2025-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_kalmar32_personalised_name_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='software_installer',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='software_installer_link',
            field=models.CharField(blank=True, help_text='Ссылка на файл инсталлятора для программного обеспечения', max_length=150, verbose_name='Инсталлятор ПО'),
        ),
    ]
