# Generated by Django 5.2.4 on 2025-10-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_kalmar32_software_installer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='software_installer_link',
        ),
    ]
