# Generated by Django 5.2.4 on 2025-11-01 10:07

import core.validators
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_kalmar32_software_installer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='kalmar',
            field=models.ForeignKey(blank=True, help_text='Связанное оборудование Kalmar32', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.kalmar32', verbose_name='Оборудование Кальмар32'),
        ),
        migrations.CreateModel(
            name='Phasar32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Уникальный серийный номер оборудования', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50), core.validators.validate_serial_number_format], verbose_name='Серийный номер')),
                ('shipment_date', models.DateField(default=datetime.date.today, help_text='Дата отгрузки оборудования со склада', verbose_name='Дата отгрузки')),
                ('case_number', models.CharField(blank=True, help_text='Номер кейса для хранения оборудования', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Номер кейса')),
                ('pc_tablet_dell_7230', models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Планшет Dell 7230')),
                ('personalised_name_tag', models.CharField(blank=True, help_text='Personalised name tag', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Персонализированная бирка')),
                ('ac_dc_power_adapter_dell', models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC адаптер питания для Dell 7230')),
                ('dc_charger_adapter_battery', models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC адаптер зарядки от батареи для Dell 7230')),
                ('ultrasonic_phased_array_pulsar', models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ультразвуковая фазированная решетка PULSAR OEM 16/128')),
                ('manual_probs_36', models.CharField(blank=True, help_text='Manual probs 36° RA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной преобразователь 36°')),
                ('has_dc_cable_battery', models.BooleanField(default=False, help_text='DC Cable from battery box', verbose_name='DC кабель от батарейного блока')),
                ('has_ethernet_cables', models.BooleanField(default=False, help_text='Ethernet cables', verbose_name='Ethernet кабель')),
                ('water_tank_with_tap', models.CharField(blank=True, help_text='Water tank with a tap', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Резервуар для воды с краном')),
                ('dc_battery_box', models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Батарейный блок DC')),
                ('ac_dc_charger_adapter_battery', models.CharField(blank=True, help_text='AC/DC Charger adapter for battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC адаптер зарядки для батареи')),
                ('calibration_block_so_3r', models.CharField(blank=True, help_text='Calibration bloc SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Калибровочный блок SO-3R')),
                ('has_repair_tool_bag', models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Ремонтный инструмент с сумкой')),
                ('has_installed_nameplate', models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Установленная табличка с серийным номером')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки по оборудованию', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Фазар32',
                'verbose_name_plural': 'Фазары32',
                'ordering': ['-shipment_date', 'serial_number'],
                'constraints': [models.UniqueConstraint(fields=('serial_number',), name='unique_phasar32_serial_number', violation_error_message='Фазар32 с таким серийным номером уже существует')],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='phasar',
            field=models.ForeignKey(blank=True, help_text='Связанное оборудование Phasar32', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.phasar32', verbose_name='Оборудование Фазар32'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['kalmar'], name='core_report_kalmar__4d682a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['phasar'], name='core_report_phasar__ae0cf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('phasar', 'report_date', 'number_to'), name='unique_report_per_phasar_by_date'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kalmar__isnull', False), ('phasar__isnull', True)), models.Q(('kalmar__isnull', True), ('phasar__isnull', False)), _connector='OR'), name='only_one_equipment_type'),
        ),
    ]
