# Generated by Django 5.2.4 on 2025-11-05 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_report_kalmar_phasar32_report_phasar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalmar32',
            name='wifi_router_address',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Адресс вай-фай роутера'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='windows_password',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Адресс вай-фай роутера'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='wifi_router_address',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Адресс вай-фай роутера'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='windows_password',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Адресс вай-фай роутера'),
        ),
    ]
