# Generated by Django 5.2.4 on 2025-11-11 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_kalmar32_wifi_router_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='manual_probs_36',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='straight_probs_0',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='left_probs',
            field=models.CharField(blank=True, help_text='Left probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Левый преобразователь'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='manual_probs',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной преобразователь'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='right_probs',
            field=models.CharField(blank=True, help_text='Right probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Правый преобразователь'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='straight_probs',
            field=models.CharField(blank=True, help_text='Straight probs PA5.0L16 0.6x10-12', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Прямой преобразователь'),
        ),
    ]
