# Generated by Django 5.2.4 on 2025-11-11 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_kalmar32_manual_probs_36_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalmar32',
            name='left_probs',
            field=models.CharField(blank=True, help_text='Left probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Левый преобразователь'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='right_probs',
            field=models.CharField(blank=True, help_text='Right probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Правый преобразователь'),
        ),
    ]
