# Generated by Django 5.2.4 on 2025-11-11 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_kalmar32_left_probs_alter_kalmar32_right_probs'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalmar32',
            name='left_probs_date',
            field=models.CharField(blank=True, help_text='Production date left probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства левого преобразователя'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='manual_probs_date',
            field=models.CharField(blank=True, help_text='Production date manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства ручного преобразователя'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='right_probs_date',
            field=models.CharField(blank=True, help_text='Production date right probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства правого преобразователя'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='straight_probs_date',
            field=models.CharField(blank=True, help_text='Production date straight probs PA5.0L16 0.6x10-12', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства прямого преобразователя'),
        ),
    ]
