# Generated by Django 5.2.4 on 2025-11-17 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_kalmar32_left_probs_date_kalmar32_manual_probs_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasar32',
            name='manual_probs_36',
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ab_back',
            field=models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Отъезжающий  блок ФР ( преобразователь одинарный)'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ab_back_date',
            field=models.CharField(blank=True, help_text='Production date AB-back PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства отъезжающего блока ФР'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ab_front',
            field=models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Наезжающий  блок ФР ( преобразователь одинарный)'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ab_front_date',
            field=models.CharField(blank=True, help_text='Production date AB-front PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства наезжающего блока ФР'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='dcn',
            field=models.CharField(blank=True, help_text='DCN P112-2,5-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок 0° ФР'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='dcn_date',
            field=models.CharField(blank=True, help_text='Production date DCN P112-2,5-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства блока 0° ФР'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ff_combo',
            field=models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='блок ФР контроля нерабочей грани головки рельса ( преобразовать комбинированный )'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='ff_combo_date',
            field=models.CharField(blank=True, help_text='Production date FF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства блока ФР контроля нерабочей грани головки рельса'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='flange_50',
            field=models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='низкочастотный блок контроля перьев подошвы рельса'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='flange_50_date',
            field=models.CharField(blank=True, help_text='Production date Flange 50 P112-0,6-50-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства низкочастотного блока контроля перьев подошвы рельса'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='gf_combo',
            field=models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='блок ФР контроля рабочей грани головки рельса ( преобразовать комбинированный )'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='gf_combo_date',
            field=models.CharField(blank=True, help_text='Production date GF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства блока ФР контроля рабочей грани головки рельса'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='manual_probs',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной наклонный ( отдельный преобразователь )'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='manual_probs_date',
            field=models.CharField(blank=True, help_text='Production date manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Дата производства ручного преобразователя'),
        ),
        migrations.AlterField(
            model_name='phasar32',
            name='has_dc_cable_battery',
            field=models.BooleanField(default=False, help_text='Dc cable battery', verbose_name='Dc cable кабель'),
        ),
    ]
