# Generated by Django 5.2.4 on 2026-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_phasar32_manual_probs_36_phasar32_ab_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='ac_dc_charger_adapter_battery',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='left_probs_date',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='manual_probs_date',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='right_probs_date',
        ),
        migrations.RemoveField(
            model_name='kalmar32',
            name='straight_probs_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='ab_back_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='ab_front_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='ac_dc_charger_adapter_battery',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='dcn_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='ff_combo_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='flange_50_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='gf_combo_date',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='manual_probs_date',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC адаптер зарядки для батареи'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC адаптер зарядки для батареи'),
        ),
    ]
