# Generated by Django 5.2.4 on 2026-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_kalmar32_ac_dc_charger_adapter_battery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='case_number',
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='HWID',
            field=models.CharField(blank=True, help_text='Hardware ID', max_length=150, verbose_name='Hardware ID'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='invoice',
            field=models.CharField(blank=True, help_text='Invoice number', max_length=100, verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='packet_list',
            field=models.CharField(blank=True, help_text='Document number', max_length=100, verbose_name='Packet list'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='HWID',
            field=models.CharField(blank=True, help_text='Hardware ID', max_length=150, verbose_name='Hardware ID'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='invoice',
            field=models.CharField(blank=True, help_text='Invoice number', max_length=100, verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='packet_list',
            field=models.CharField(blank=True, help_text='Document number', max_length=100, verbose_name='Packet list'),
        ),
    ]
