# Generated by Django 5.2.4 on 2026-01-29 08:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_kalmar32_case_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalmar32',
            name='HWID',
        ),
        migrations.RemoveField(
            model_name='phasar32',
            name='HWID',
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='windows_password',
            field=models.CharField(blank=True, help_text='Пароль учетной записи Windows', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Пароль Windows'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.CharField(blank=True, default='', help_text='Версия лицензионного ключа', max_length=50, verbose_name='Версия лицензии')),
                ('product', models.CharField(help_text='Название продукта', max_length=100, verbose_name='Продукт')),
                ('company_name', models.CharField(blank=True, default='', help_text='Название компании=', max_length=200, verbose_name='Название компании')),
                ('host_hwid', models.CharField(help_text='Hardware ID хоста', max_length=150, verbose_name='Host HWID')),
                ('device_hwid', models.CharField(blank=True, default='', help_text='Hardware ID устройства', max_length=150, verbose_name='Device HWID')),
                ('exp', models.DateField(default=datetime.date(2100, 1, 1), help_text='Дата истечения срока действия лицензии', verbose_name='Дата истечения')),
                ('features', models.JSONField(default=dict, help_text='Дополнительные функции в формате JSON', verbose_name='Функциональность')),
                ('signature', models.TextField(blank=True, help_text='Цифровая подпись лицензии', verbose_name='Подпись')),
                ('license_key', models.TextField(help_text='Сгенерированный лицензионный ключ                 в формате base64url(payload).base64url(signature)', unique=True, verbose_name='Лицензионный ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания лицензии', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления лицензии', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('license_key',), name='unique_license_key')],
            },
        ),
        migrations.AddField(
            model_name='kalmar32',
            name='license',
            field=models.OneToOneField(blank=True, help_text='Лицензия для этого оборудования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalmar32_license', to='core.license', verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='license',
            field=models.OneToOneField(blank=True, help_text='Лицензия для этого оборудования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phasar32_license', to='core.license', verbose_name='Лицензия'),
        ),
    ]
