# Generated by Django 5.2.4 on 2026-01-30 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_kalmar32_hwid_remove_phasar32_hwid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasar32',
            name='windows_password',
            field=models.CharField(blank=True, help_text='Windows password', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Пароль для виндоус'),
        ),
    ]
