# Generated by Django 5.2.4 on 2026-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_phasar32_windows_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.TextField(help_text='Сгенерированный лицензионный ключ                 в формате base64url(payload).base64url(signature)', verbose_name='Лицензионный ключ'),
        ),
    ]
