# Generated by Django 5.2.4 on 2026-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_license_license_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='license',
            name='unique_license_key',
        ),
    ]
