# Generated by Django 5.2.4 on 2026-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_license_unique_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalmar32',
            name='license_password',
            field=models.CharField(default='Votum12901', help_text='Пароль для активации лицензии', max_length=100, verbose_name='License password'),
        ),
        migrations.AddField(
            model_name='phasar32',
            name='license_password',
            field=models.CharField(default='Votum12901', help_text='Пароль для активации лицензии', max_length=100, verbose_name='License password'),
        ),
    ]
