# Generated by Django 5.2.4 on 2026-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_kalmar32_license_password_phasar32_license_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalmar32',
            name='rail_type',
            field=models.CharField(choices=[('P65', 'P65'), ('IRS52', 'IRS52'), ('UIC60', 'UIC60')], default='P65', help_text='Тип рельсов (P65, IRS52, UIC60)', max_length=10, verbose_name='Тип рельс'),
        ),
    ]
