# Generated by Django 5.2.4 on 2026-03-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_kalmar32_rail_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasar32',
            name='personalised_name_tag',
        ),
    ]
