# Generated by Django 5.2.4 on 2026-03-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_phasar32_personalised_name_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phasar32',
            new_name='Phasar01',
        ),

        migrations.AlterField(
            model_name='report',
            name='phasar',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to='core.phasar01',
                help_text='Связанное оборудование Phasar01',
                verbose_name='Оборудование Фазар01',
            ),
        ),
    ]