# Generated by Django 5.2.4 on 2026-03-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_phasar32_license_phasar01_alter_report_phasar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasar01',
            options={'ordering': ['-shipment_date', 'serial_number'], 'verbose_name': 'Фазар01', 'verbose_name_plural': 'Фазары01'},
        ),
        migrations.RemoveConstraint(
            model_name='phasar01',
            name='unique_phasar32_serial_number',
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='license',
            field=models.OneToOneField(blank=True, help_text='Лицензия для этого оборудования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phasar01_license', to='core.license', verbose_name='Лицензия'),
        ),
        migrations.AddConstraint(
            model_name='phasar01',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_phasar01_serial_number', violation_error_message='Фазар01 с таким серийным номером уже существует'),
        ),
    ]
