# Generated by Django 5.2.4 on 2026-03-24 10:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_phasar01_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phasar02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Уникальный серийный номер оборудования', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='Серийный номер')),
                ('license_password', models.CharField(default='Votum12901', help_text='Пароль для активации лицензии', max_length=100, verbose_name='License password')),
                ('shipment_date', models.DateField(default=datetime.date.today, help_text='Дата отгрузки оборудования со склада', verbose_name='Дата отгрузки')),
                ('invoice', models.CharField(blank=True, help_text='Invoice number', max_length=100, verbose_name='Invoice')),
                ('packet_list', models.CharField(blank=True, help_text='Document number', max_length=100, verbose_name='Packet list')),
                ('pc_tablet_dell_7230', models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Планшет Dell 7230')),
                ('ac_dc_power_adapter_dell', models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC адаптер питания для Dell 7230')),
                ('dc_charger_adapter_battery', models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC адаптер зарядки от батареи для Dell 7230')),
                ('ultrasonic_phased_array_pulsar_left', models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ультразвуковая фазированная решетка PULSAR OEM 16/128 (ЛЕВЫЙ)')),
                ('dcn_left', models.CharField(blank=True, help_text='DCN P112-2,5-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок 0° ФР (ЛЕВЫЙ)')),
                ('ab_back_left', models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Отъезжающий блок ФР (ЛЕВЫЙ)')),
                ('gf_combo_left', models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок ФР рабочей грани (ЛЕВЫЙ)')),
                ('ff_combo_left', models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок ФР нерабочей грани (ЛЕВЫЙ)')),
                ('ab_front_left', models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Наезжающий блок ФР (ЛЕВЫЙ)')),
                ('flange_50_left', models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Низкочастотный блок подошвы (ЛЕВЫЙ)')),
                ('manual_probs_left', models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17 (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной наклонный преобразователь (ЛЕВЫЙ)')),
                ('has_dc_cable_battery_left', models.BooleanField(default=False, help_text='DC Cable from Battery (LEFT)', verbose_name='DC кабель от батареи (ЛЕВЫЙ)')),
                ('has_ethernet_cables_left', models.BooleanField(default=False, help_text='Ethernet Cables (LEFT)', verbose_name='Ethernet кабель (ЛЕВЫЙ)')),
                ('ultrasonic_phased_array_pulsar_right', models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ультразвуковая фазированная решетка PULSAR OEM 16/128 (ПРАВЫЙ)')),
                ('dcn_right', models.CharField(blank=True, help_text='DCN P112-2,5-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок 0° ФР (ПРАВЫЙ)')),
                ('ab_back_right', models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Отъезжающий блок ФР (ПРАВЫЙ)')),
                ('gf_combo_right', models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок ФР рабочей грани (ПРАВЫЙ)')),
                ('ff_combo_right', models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Блок ФР нерабочей грани (ПРАВЫЙ)')),
                ('ab_front_right', models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Наезжающий блок ФР (ПРАВЫЙ)')),
                ('flange_50_right', models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Низкочастотный блок подошвы (ПРАВЫЙ)')),
                ('manual_probs_right', models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17 (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ручной наклонный преобразователь (ПРАВЫЙ)')),
                ('has_dc_cable_battery_right', models.BooleanField(default=False, help_text='DC Cable from Battery (RIGHT)', verbose_name='DC кабель от батареи (ПРАВЫЙ)')),
                ('has_ethernet_cables_right', models.BooleanField(default=False, help_text='Ethernet Cables (RIGHT)', verbose_name='Ethernet кабель (ПРАВЫЙ)')),
                ('water_tank_with_tap_left', models.CharField(blank=True, help_text='Water tank with a tap (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Резервуар для воды с краном (ЛЕВЫЙ)')),
                ('water_tank_with_tap_right', models.CharField(blank=True, help_text='Water tank with a tap (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Резервуар для воды с краном (ПРАВЫЙ)')),
                ('dc_battery_box_left', models.CharField(blank=True, help_text='DC Battery box established (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Батарейный блок DC (ЛЕВЫЙ)')),
                ('dc_battery_box_right', models.CharField(blank=True, help_text='DC Battery box established (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Батарейный блок DC (ПРАВЫЙ)')),
                ('has_ac_dc_charger_adapter_battery_left', models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery (LEFT)', verbose_name='AC/DC адаптер зарядки для батареи (ЛЕВЫЙ)')),
                ('has_ac_dc_charger_adapter_battery_right', models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery (RIGHT)', verbose_name='AC/DC адаптер зарядки для батареи (ПРАВЫЙ)')),
                ('calibration_block_so_3r_left', models.CharField(blank=True, help_text='Calibration bloc SO-3R (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Калибровочный блок SO-3R (ЛЕВЫЙ)')),
                ('calibration_block_so_3r_right', models.CharField(blank=True, help_text='Calibration bloc SO-3R (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Калибровочный блок SO-3R (ПРАВЫЙ)')),
                ('has_repair_tool_bag_left', models.BooleanField(default=False, help_text='Small repair tool with bag (LEFT)', verbose_name='Ремонтный инструмент с сумкой (ЛЕВЫЙ)')),
                ('has_repair_tool_bag_right', models.BooleanField(default=False, help_text='Small repair tool with bag (RIGHT)', verbose_name='Ремонтный инструмент с сумкой (ПРАВЫЙ)')),
                ('has_installed_nameplate_left', models.BooleanField(default=False, help_text='Installed nameplate with serial number (LEFT)', verbose_name='Установленная табличка с серийным номером (ЛЕВЫЙ)')),
                ('has_installed_nameplate_right', models.BooleanField(default=False, help_text='Installed nameplate with serial number (RIGHT)', verbose_name='Установленная табличка с серийным номером (ПРАВЫЙ)')),
                ('wifi_router_address', models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Адрес Wi-Fi роутера')),
                ('windows_password', models.CharField(blank=True, help_text='Windows password', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Пароль для Windows')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки по оборудованию', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Фазар02',
                'verbose_name_plural': 'Фазары02',
                'ordering': ['-shipment_date', 'serial_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-created_at'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_kalmar_by_date',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_phasar_by_date',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='only_one_equipment_type',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='core_report_kalmar__4d682a_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='core_report_phasar__ae0cf6_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='kalmar',
        ),
        migrations.RemoveField(
            model_name='report',
            name='phasar',
        ),
        migrations.AddField(
            model_name='report',
            name='kalmar32',
            field=models.ForeignKey(blank=True, help_text='Связанное оборудование Kalmar32', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.kalmar32', verbose_name='Оборудование Кальмар32'),
        ),
        migrations.AddField(
            model_name='report',
            name='phasar01',
            field=models.ForeignKey(blank=True, help_text='Связанное оборудование Phasar01', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.phasar01', verbose_name='Оборудование Фазар01'),
        ),
        migrations.AlterField(
            model_name='license',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Company name', max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation date of the license', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='license',
            name='device_hwid',
            field=models.CharField(blank=True, default='', help_text='Hardware ID of the device', max_length=150, verbose_name='Device HWID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='exp',
            field=models.DateField(default=datetime.date(2100, 1, 1), help_text='Expiration date of the license', verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='features',
            field=models.JSONField(default=dict, help_text='Additional features in JSON format', verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='license',
            name='host_hwid',
            field=models.CharField(help_text='Hardware ID of the host', max_length=150, verbose_name='Host HWID'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.TextField(help_text='Generated license key in base64url(payload).base64url(signature) format', verbose_name='License key'),
        ),
        migrations.AlterField(
            model_name='license',
            name='product',
            field=models.CharField(help_text='Product name', max_length=100, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='license',
            name='signature',
            field=models.TextField(blank=True, help_text='Digital signature of the license', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='license',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update date of the license', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='license',
            name='ver',
            field=models.CharField(blank=True, default='', help_text='Version of the license key', max_length=50, verbose_name='License version'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='license',
            field=models.OneToOneField(blank=True, help_text='Лицензия для этого оборудования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phasar02_license', to='core.license', verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='report',
            name='phasar02',
            field=models.ForeignKey(blank=True, help_text='Связанное оборудование Phasar02', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.phasar02', verbose_name='Оборудование Фазар02'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['kalmar32'], name='core_report_kalmar3_fb2183_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['phasar01'], name='core_report_phasar0_809b50_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['phasar02'], name='core_report_phasar0_5a79a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='phasar02',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_phasar02_serial_number', violation_error_message='Фазар02 с таким серийным номером уже существует'),
        ),
    ]
