# Generated by Django 5.2.4 on 2026-03-24 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_phasar02_alter_license_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasar02',
            name='calibration_block_so_3r_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='calibration_block_so_3r_right',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='dc_battery_box_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='dc_battery_box_right',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_ac_dc_charger_adapter_battery_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_ac_dc_charger_adapter_battery_right',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_installed_nameplate_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_installed_nameplate_right',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_repair_tool_bag_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='has_repair_tool_bag_right',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='water_tank_with_tap_left',
        ),
        migrations.RemoveField(
            model_name='phasar02',
            name='water_tank_with_tap_right',
        ),
        migrations.AddField(
            model_name='phasar02',
            name='calibration_block_so_3r',
            field=models.CharField(blank=True, help_text='Calibration bloc SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Калибровочный блок SO-3R'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='dc_battery_box',
            field=models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Батарейный блок DC'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC адаптер зарядки для батареи'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='has_installed_nameplate',
            field=models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Установленная табличка с серийным номером'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='has_repair_tool_bag',
            field=models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Ремонтный инструмент с сумкой'),
        ),
        migrations.AddField(
            model_name='phasar02',
            name='water_tank_with_tap',
            field=models.CharField(blank=True, help_text='Water tank with a tap', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Резервуар для воды с краном'),
        ),
    ]
