# Generated by Django 5.2.4 on 2026-07-22 13:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_phasar02_calibration_block_so_3r_left_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kalmar32',
            options={'ordering': ['-shipment_date', 'serial_number'], 'verbose_name': 'Kalmar32', 'verbose_name_plural': 'Kalmar32 items'},
        ),
        migrations.AlterModelOptions(
            name='phasar01',
            options={'ordering': ['-shipment_date', 'serial_number'], 'verbose_name': 'Phasar01', 'verbose_name_plural': 'Phasar01 items'},
        ),
        migrations.AlterModelOptions(
            name='phasar02',
            options={'ordering': ['-shipment_date', 'serial_number'], 'verbose_name': 'Phasar02', 'verbose_name_plural': 'Phasar02 items'},
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='ac_dc_power_adapter_dell',
            field=models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC power adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='calibration_block_so_3r',
            field=models.CharField(blank=True, help_text='Calibration bloc SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Calibration block SO-3R'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='dc_battery_box',
            field=models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC Battery box'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='dc_charger_adapter_battery',
            field=models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC battery charger adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC charger adapter for battery'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='has_dc_cable_battery',
            field=models.BooleanField(default=False, help_text='DC Cable from battery box', verbose_name='DC cable from battery box'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='has_ethernet_cables',
            field=models.BooleanField(default=False, help_text='Ethernet cables', verbose_name='Ethernet cable'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='has_installed_nameplate',
            field=models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Installed nameplate with serial number'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='has_repair_tool_bag',
            field=models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Repair tool with bag'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='left_probs',
            field=models.CharField(blank=True, help_text='Left probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Left probe'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='license',
            field=models.OneToOneField(blank=True, help_text='License for this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalmar32_license', to='core.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='license_password',
            field=models.CharField(default='Votum12901', help_text='Password for license activation', max_length=100, verbose_name='License password'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='manual_probs',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Manual probe'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes regarding the equipment', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='pc_tablet_dell_7230',
            field=models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Dell 7230 Tablet'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='rail_type',
            field=models.CharField(choices=[('P65', 'P65'), ('IRS52', 'IRS52'), ('UIC60', 'UIC60')], default='P65', help_text='Rail type (P65, IRS52, UIC60)', max_length=10, verbose_name='Rail type'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='right_probs',
            field=models.CharField(blank=True, help_text='Right probs PA2.25L16 1.1x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Right probe'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number of the equipment', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='shipment_date',
            field=models.DateField(default=datetime.date.today, help_text='Shipment date of the equipment from the warehouse', verbose_name='Shipment date'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='straight_probs',
            field=models.CharField(blank=True, help_text='Straight probs PA5.0L16 0.6x10-12', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Straight probe'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='ultrasonic_phased_array_pulsar',
            field=models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/64 established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ultrasonic phased array PULSAR OEM 16/64'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='wifi_router_address',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Wi-Fi router address'),
        ),
        migrations.AlterField(
            model_name='kalmar32',
            name='windows_password',
            field=models.CharField(blank=True, help_text='Windows account password', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Windows password'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='ab_back',
            field=models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Trailing PA block (single probe)'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='ab_front',
            field=models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Leading PA block (single probe)'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='ac_dc_power_adapter_dell',
            field=models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC power adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='calibration_block_so_3r',
            field=models.CharField(blank=True, help_text='Calibration block SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Calibration block SO-3R'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='dc_battery_box',
            field=models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC Battery box'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='dc_charger_adapter_battery',
            field=models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC battery charger adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='dcn',
            field=models.CharField(blank=True, help_text='DCN P112-2,5-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='0° PA Block'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='ff_combo',
            field=models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Rail head field side inspection PA block (combined probe)'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='flange_50',
            field=models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Low-frequency rail base flange inspection block'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='gf_combo',
            field=models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Rail head gauge face inspection PA block (combined probe)'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC charger adapter for battery'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='has_dc_cable_battery',
            field=models.BooleanField(default=False, help_text='DC cable battery', verbose_name='DC cable'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='has_ethernet_cables',
            field=models.BooleanField(default=False, help_text='Ethernet cables', verbose_name='Ethernet cable'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='has_installed_nameplate',
            field=models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Installed nameplate with serial number'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='has_repair_tool_bag',
            field=models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Repair tool with bag'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='license',
            field=models.OneToOneField(blank=True, help_text='License for this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phasar01_license', to='core.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='license_password',
            field=models.CharField(default='Votum12901', help_text='Password for license activation', max_length=100, verbose_name='License password'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='manual_probs',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Manual angle probe (separate probe)'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes regarding the equipment', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='pc_tablet_dell_7230',
            field=models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Dell 7230 Tablet'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number of the equipment', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='shipment_date',
            field=models.DateField(default=datetime.date.today, help_text='Shipment date of the equipment from the warehouse', verbose_name='Shipment date'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='ultrasonic_phased_array_pulsar',
            field=models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ultrasonic phased array PULSAR OEM 16/128'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='water_tank_with_tap',
            field=models.CharField(blank=True, help_text='Water tank with a tap', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Water tank with tap'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='wifi_router_address',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Wi-Fi router address'),
        ),
        migrations.AlterField(
            model_name='phasar01',
            name='windows_password',
            field=models.CharField(blank=True, help_text='Windows password', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Windows password'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ab_back_left',
            field=models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Trailing PA block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ab_back_right',
            field=models.CharField(blank=True, help_text='AB-back PA2,5L16 1,1x10-17-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Trailing PA block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ab_front_left',
            field=models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Leading PA block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ab_front_right',
            field=models.CharField(blank=True, help_text='AB-front PA2,5L16 1,1x10-17-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Leading PA block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ac_dc_power_adapter_dell',
            field=models.CharField(blank=True, help_text='AC/DC Power adapter for Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='AC/DC power adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='calibration_block_so_3r',
            field=models.CharField(blank=True, help_text='Calibration block SO-3R', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Calibration block SO-3R'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='dc_battery_box',
            field=models.CharField(blank=True, help_text='DC Battery box established', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC Battery box'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='dc_charger_adapter_battery',
            field=models.CharField(blank=True, help_text='DC Charger adapter for Dell 7230 from battery', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='DC battery charger adapter for Dell 7230'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='dcn_left',
            field=models.CharField(blank=True, help_text='DCN P112-2,5-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='0° PA Block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='dcn_right',
            field=models.CharField(blank=True, help_text='DCN P112-2,5-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='0° PA Block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ff_combo_left',
            field=models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Field side PA block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ff_combo_right',
            field=models.CharField(blank=True, help_text='FF combo 2PA2,5L16 0,6x10-10-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Field side PA block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='flange_50_left',
            field=models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Low-frequency rail base block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='flange_50_right',
            field=models.CharField(blank=True, help_text='Flange 50 P112-0,6-50-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Low-frequency rail base block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='gf_combo_left',
            field=models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Gauge face PA block (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='gf_combo_right',
            field=models.CharField(blank=True, help_text='GF combo 2PA2,5L16 0,6x10-10-F (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Gauge face PA block (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_ac_dc_charger_adapter_battery',
            field=models.BooleanField(default=False, help_text='AC/DC Charger adapter for battery', verbose_name='AC/DC charger adapter for battery'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_dc_cable_battery_left',
            field=models.BooleanField(default=False, help_text='DC Cable from Battery (LEFT)', verbose_name='DC cable from battery (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_dc_cable_battery_right',
            field=models.BooleanField(default=False, help_text='DC Cable from Battery (RIGHT)', verbose_name='DC cable from battery (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_ethernet_cables_left',
            field=models.BooleanField(default=False, help_text='Ethernet Cables (LEFT)', verbose_name='Ethernet cable (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_ethernet_cables_right',
            field=models.BooleanField(default=False, help_text='Ethernet Cables (RIGHT)', verbose_name='Ethernet cable (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_installed_nameplate',
            field=models.BooleanField(default=False, help_text='Installed nameplate with serial number', verbose_name='Installed nameplate with serial number'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='has_repair_tool_bag',
            field=models.BooleanField(default=False, help_text='Small repair tool with bag', verbose_name='Repair tool with bag'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='license',
            field=models.OneToOneField(blank=True, help_text='License for this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phasar02_license', to='core.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='license_password',
            field=models.CharField(default='Votum12901', help_text='Password for license activation', max_length=100, verbose_name='License password'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='manual_probs_left',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17 (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Manual angle probe (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='manual_probs_right',
            field=models.CharField(blank=True, help_text='Manual probs PA2.25L16 0.9x10-17 (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Manual angle probe (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes regarding the equipment', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='pc_tablet_dell_7230',
            field=models.CharField(blank=True, help_text='PC tablet Latitude Dell 7230', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Dell 7230 Tablet'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number of the equipment', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)], verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='shipment_date',
            field=models.DateField(default=datetime.date.today, help_text='Shipment date of the equipment from the warehouse', verbose_name='Shipment date'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ultrasonic_phased_array_pulsar_left',
            field=models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established (LEFT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ultrasonic phased array PULSAR OEM 16/128 (LEFT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='ultrasonic_phased_array_pulsar_right',
            field=models.CharField(blank=True, help_text='Ultrasonic phased array PULSAR OEM 16/128 established (RIGHT)', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Ultrasonic phased array PULSAR OEM 16/128 (RIGHT)'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='water_tank_with_tap',
            field=models.CharField(blank=True, help_text='Water tank with a tap', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Water tank with tap'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='wifi_router_address',
            field=models.CharField(blank=True, help_text='WiFi router address', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Wi-Fi router address'),
        ),
        migrations.AlterField(
            model_name='phasar02',
            name='windows_password',
            field=models.CharField(blank=True, help_text='Windows password', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Windows password'),
        ),
        migrations.AlterConstraint(
            model_name='kalmar32',
            name='unique_serial_number',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_serial_number', violation_error_message='A Kalmar32 item with this serial number already exists'),
        ),
        migrations.AlterConstraint(
            model_name='phasar01',
            name='unique_phasar01_serial_number',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_phasar01_serial_number', violation_error_message='A Phasar01 item with this serial number already exists'),
        ),
        migrations.AlterConstraint(
            model_name='phasar02',
            name='unique_phasar02_serial_number',
            constraint=models.UniqueConstraint(fields=('serial_number',), name='unique_phasar02_serial_number', violation_error_message='A Phasar02 item with this serial number already exists'),
        ),
    ]
