# Generated by Django 5.2.4 on 2026-08-11 10:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_kalmar32_options_alter_phasar01_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kalmar32', 'Kalmar 32+'), ('phasarsl', 'Phasar 01 (SL)'), ('phasarlt', 'Phasar 01 (LT)'), ('phasardl', 'Phasar 02 (DL)'), ('wizard6', 'Wizard 6'), ('wizard8', 'Wizard 8'), ('chameleon32', 'Chameleon 32+')], max_length=50, verbose_name='Model name')),
                ('version', models.CharField(help_text='Hardware/Plant version, e.g. Ver_1, Ver2 Plant', max_length=50, verbose_name='Model version')),
                ('type_rail', models.CharField(choices=[('UIC60', 'UIC 60'), ('IRS52', 'IRS 52'), ('R65', 'R65 / P65'), ('NONE', 'None')], default='NONE', max_length=10, verbose_name='Rail type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Model Variant',
                'verbose_name_plural': 'Model Variants',
                'constraints': [models.UniqueConstraint(fields=('name', 'version', 'type_rail'), name='unique_model_variant')],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('kalmar32', 'Kalmar 32+'), ('phasarsl', 'Phasar 01 (SL)'), ('phasarlt', 'Phasar 01 (LT)'), ('phasardl', 'Phasar 02 (DL)'), ('wizard6', 'Wizard 6'), ('wizard8', 'Wizard 8'), ('chameleon32', 'Chameleon 32+')], help_text='Base model name this scheme belongs to', max_length=50, verbose_name='Model name')),
                ('version', models.PositiveIntegerField(help_text='Sequential scheme layout version', verbose_name='Scheme version')),
                ('fields_description', models.JSONField(default=dict, verbose_name='Fields description')),
                ('is_latest', models.BooleanField(default=False, verbose_name='Is latest scheme')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'constraints': [models.UniqueConstraint(fields=('model_name', 'version'), name='unique_scheme_version_per_model_name')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Serial number')),
                ('invoice', models.CharField(blank=True, max_length=100, verbose_name='Invoice')),
                ('packet_list', models.CharField(blank=True, max_length=100, verbose_name='Packet list')),
                ('shipment_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Shipment date')),
                ('other_data', models.JSONField(blank=True, default=dict, verbose_name='Dynamic data')),
                ('license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.license')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='core.model', verbose_name='Model Variant')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='core.scheme', verbose_name='Fields Scheme')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment items',
            },
        ),
    ]
