# Generated by Django 5.2.4 on 2026-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_model_scheme_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='type_rail',
            field=models.CharField(choices=[('UIC60', 'UIC 60'), ('IRS52', 'IRS 52'), ('R65', 'R65'), ('NONE', 'None')], default='NONE', max_length=10, verbose_name='Rail type'),
        ),
    ]
