# Generated by Django 5.2.4 on 2026-08-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_model_type_rail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
