# Generated by Django 5.2.4 on 2026-09-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_delete_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="Internal name",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Display name", max_length=100, verbose_name="Display name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Equipment description", verbose_name="Description"
                    ),
                ),
                (
                    "installer_path",
                    models.CharField(
                        blank=True,
                        help_text="Installer file name",
                        max_length=100,
                        verbose_name="Installer filename",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Equipment type",
                "verbose_name_plural": "Equipment types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="model",
            options={},
        ),
        migrations.AlterModelOptions(
            name="scheme",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="model",
            name="unique_model_variant",
        ),
        migrations.RemoveConstraint(
            model_name="scheme",
            name="unique_scheme_version_per_model_name",
        ),
        migrations.RemoveField(
            model_name="model",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="model_name",
        ),
        migrations.AddField(
            model_name="model",
            name="equipment_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variants",
                to="core.equipmenttype",
                verbose_name="Equipment type",
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="equipment_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schemes",
                to="core.equipmenttype",
                verbose_name="Equipment type",
            ),
        ),
        migrations.AddConstraint(
            model_name="model",
            constraint=models.UniqueConstraint(
                fields=("equipment_type", "version", "type_rail"), name="unique_model_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheme",
            constraint=models.UniqueConstraint(
                fields=("equipment_type", "version"), name="unique_scheme_version_per_type"
            ),
        ),
    ]
